[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kyc_blockchain = "95DUxFM1maisbvcECkm7cb9YE9xdLLFad5RJA6Q3GdV3"
nft_mint = "ExgbQW44gemTQq6jzciCsdmyKg5u9vGeGc1iUR6PxnjF"
presale = "CQrfC25gmpxo8Fm4zGf8aYFyzqexoyZqJL76Cw1HT4En"
smart_contract = "6mjNJ1d4uGJt6XgBRd6bUd7G7ZWsYqLmQkoXnEjWo8GR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/kyc-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "cargo build-bpf --release"

[programs.localnet]
smart_contract = "FbDDiNnLj9ozP4GCUMVK3bgHHmLkmuhceKwxtdUPKDkJ"